[package]
name = "nl-find"
version = "0.1.0"
authors = ["Adrian L Flanagan <a.lloyd.flanagan@gmail.com>"]
edition = "2018"
build = "build.rs"

[build-dependencies]
lalrpop = "0.16.2"

[dependencies]
lalrpop-util = "0.16.2"
regex = "1.1.0"
