[package]
name = "nl-find"
version = "0.1.0"
authors = ["Adrian L Flanagan <a.lloyd.flanagan@gmail.com>"]
edition = "2018"

[dependencies]
regex = "1.1.0"
clap = {version = "2.32.0", features = ["yaml"]}
libc = "0.2.46"
